### ISSUE TITLE
Calculate forces node disappears when graph is saved in Unity 2019.1.8f1

### ISSUE THREAD

**Issue by twn-box** [thinksquirrel/fluviofx#25]
I thought it was strange when I noticed forces weren't being applied in my simulation and have since realized its because every time I save the graph the "calculate forces" node is removed. 

<img width="374" alt="L7HPIsy7e8" src="https://user-images.githubusercontent.com/51932977/62174758-e62ac000-b2ef-11e9-988a-fa61e69445f5.png">

<img width="161" alt="IqbTqI28IV" src="https://user-images.githubusercontent.com/51932977/62174756-e5922980-b2ef-11e9-8552-148d4f5768ce.png">

<img width="385" alt="DZO3Zn1fUC" src="https://user-images.githubusercontent.com/51932977/62174755-e5922980-b2ef-11e9-9695-c9b176260583.png">

**Comment by lmontoute** [comment]
This _should_ be resolved in the latest version. You may need to fully reinstall for things to take effect though.

Let me know if that works for you, since I never nailed down the cause but my update seemed to make it stop. I know it's pretty aggravating :(

**Comment by twn-box** [comment]
I was able to fix it by copying the folder & opening it as another project!
