### ISSUE TITLE
Add additional integrators

### ISSUE THREAD

**Issue by lilyvelour** [thinksquirrel/fluviofx#3]
A while back, we had a focused effort with Fluvio on improving solver stability by utilizing different integration methods. These never shipped to Asset Store users. During our research process, we implemented the following integrators:

- Semi-Implicit Euler (implemented)
~~- Forward Euler~~
- Verlet
- Velocity Verlet
~~- Parker–Sochacki (experimental)~~

Let's look into implementing these integrators into FluvioFX as well.

**Comment by lmontoute** [comment]
Updated the list of integrators (we were actually using semi-implicit Euler without a position update for historical reasons). Removed forward Euler as I'm not sure it's worth it...ever.

This is in the works (Verlet and Velocity Verlet are both completed so far). Still on the fence about even including Velocity Verlet, however...

**Comment by lmontoute** [comment]
Also going to cut P-S for now. While a promising numerical method, the current implementation would likely slow performance down too much with an additional neighbor search.
