### ISSUE TITLE
Namespace CollisionCone errors

### ISSUE THREAD

**Issue by GianMauricio** [thinksquirrel/fluviofx#53]
Hello! 

I was recently recommended FluvioFX by one of my professors, after importing it into my current project, I got the following error message:

![image](https://user-images.githubusercontent.com/44298742/175754295-d6a1c94c-df9e-4f30-8c58-5656299bb05a.png)

I'm not sure what's going on since I tried to open the script the errors were supposedly coming from (CollisionCylinder.cs) but Visual Studio didn't show any script errors. I would like to know if there's any documentation that I could reference for this? 

Thank you for your time and the FluvioFX package, it's really cool and I would really love to make it work, if there is anything else I can provide in the way of information then I would love to help.

Addl. Info: 
Unity Version: 2020.3.26f1
Visual Effect Graph Version: 10.8.1

End of Unity Compiler log error snippet:
-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/FluvioFX.Editor.dll
Microsoft (R) Visual C# Compiler version 3.5.0-dev-20359-01 (8da8ba0c)
Copyright (C) Microsoft Corporation. All rights reserved.

Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(9,49): error CS0234: The type or namespace name 'CollisionCone' does not exist in the namespace 'UnityEditor.VFX.Block' (are you missing an assembly reference?)
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(11,32): error CS0115: 'CollisionCone.name': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(34,45): error CS0115: 'CollisionCone.includes': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(36,57): error CS0115: 'CollisionCone.parameters': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(38,62): error CS0115: 'CollisionCone.inputProperties': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(40,55): error CS0115: 'CollisionCone.attributes': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(43,32): error CS0115: 'CollisionCone.source': no suitable method found to override
-----EndCompilerOutput---------------
- Finished script compilation in 1.580733 seconds
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(9,49): error CS0234: The type or namespace name 'CollisionCone' does not exist in the namespace 'UnityEditor.VFX.Block' (are you missing an assembly reference?)
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(11,32): error CS0115: 'CollisionCone.name': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(34,45): error CS0115: 'CollisionCone.includes': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(36,57): error CS0115: 'CollisionCone.parameters': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(38,62): error CS0115: 'CollisionCone.inputProperties': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(40,55): error CS0115: 'CollisionCone.attributes': no suitable method found to override
Library\PackageCache\com.fluvio.fx@ef71b9444e\Editor\Blocks\Collision\CollisionCylinder.cs(43,32): error CS0115: 'CollisionCone.source': no suitable method found to override
Refresh completed in 0.003719 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 2.910ms
Refresh completed in 0.002573 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 2.362ms
Refresh completed in 0.002849 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 2.795ms
<RI> Initialized touch support.

Refresh completed in 0.004195 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 2.859ms
Refresh completed in 0.004004 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 3.089ms
Refresh completed in 0.004077 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 2.943ms

**Comment by GianMauricio** [comment]
Solved by using this fork of Fluvio: https://github.com/mjducharme/fluviofx

**Comment by lilyvelour** [comment]
Ah yeah, this was renamed in 2021 unfortunately! For 2020 I'd recommend the fork, since I unfortunately can't support multiple LTS releases right now.

(if someone wants to enable support for 2020 and 2021 at the same time, I'm open to PRs!)
