### ISSUE TITLE
Make project as archived

### ISSUE THREAD

**Issue by 0xF6** [thinksquirrel/fluviofx#54]
don't confuse people

**Comment by andybak** [comment]
There was a commit 6 months ago. Don't know about you but I've got active projects that have commits less frequently than that.

**Comment by 0xF6** [comment]
>Don't know about you but I've got active projects that have commits less frequently than that.

Yes, but it project not work in latest engine versions and LTS

**Comment by lilyvelour** [comment]
As @andybak mentioned, this project is still very much active! At the moment I'm not tracking every single Unity and VFX graph release, but if there's a specific version you need to support I'd be happy to take a look at a PR!
