### ISSUE TITLE
Legacy Unity (5) Support?

### ISSUE THREAD

**Issue by AtlasTabula** [thinksquirrel/fluviofx#55]
Are there any available archives for Fluvio supporting the older versions of Unity, like Unity 5?

I'm on an old Pro license and would like to remain on it, but need a robust fluid simulation, and remember using Fluvio free in the past but obviously that's not on the Asset Store anymore.

I don't suppose anyone still has the code for it?

**Comment by lilyvelour** [comment]
Unfortunately, I'm unable to readily hand out that code and the license prevents others from distributing it. :( I'd highly recommend upgrading to FluvioFX!

If you're feeling adventurous, the shaders here are pretty much the same, though back in the Unity 5 days it was all done via C# manipulation of particle arrays, so you'd want to translate things back to C#.

Thank you for being a longtime supporter though, it means a lot to me after working on this project for...whew, it's been over a decade now!
