### ISSUE TITLE
FluvioFXInstall.cs

### ISSUE THREAD

**Issue by Boo0317** [thinksquirrel/fluviofx#9]
`.Invoke<UnityEditor.PackageManager.PackageInfo[]>("GetAll");`  on Line 179.
UnityEditor namespace does not contain PackageManager before Unity2017

**Comment by lmontoute** [comment]
Hi @Boo0317,

Thanks for the report. FluvioFX requires the Package Manager and VFX graph, so only Unity 2018.3+ is supported. I've added this to the README.
